management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,flyway
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

info:
  app:
    name: ${APP_NAME:lgb}
    description: Spring Boot application
    version: ${APP_VERSION:0.0.1}